const bankCodes = {
    baac:	"Bank for Agriculture and Agricultural Cooperatives",
    bay:	"Bank of Ayudhya (Krungsri)",
    bbl:	"Bangkok Bank",
    bnp:	"BNP Paribas",
    boa:	"Bank of America",
    cacib:	"Crédit Agricole",
    cimb:	"CIMB Thai Bank",
    citi:	"Citibank",
    db:	"Deutsche Bank",
    ghb:	"Government Housing Bank",
    gsb:	"Government Savings Bank",
    hsbc:	"Hongkong and Shanghai Banking Corporation",
    ibank:	"Islamic Bank of Thailand",
    icbc:	"Industrial and Commercial Bank of China (Thai)",
    jpm:	"J.P. Morgan",
    kbank:	"Kasikornbank",
    kk:	"Kiatnakin Bank",
    ktb:	"Krungthai Bank",
    lhb:	"Land and Houses Bank",
    mb:	"Mizuho Bank",
    mega:	"Mega International Commercial Bank",
    mufg:	"Bank of Tokyo-Mitsubishi UFJ",
    rbs:	"Royal Bank of Scotland",
    sc:	"Standard Chartered (Thai)",
    scb:	"Siam Commercial Bank",
    smbc:	"Sumitomo Mitsui Banking Corporation",
    tcrb:	"Thai Credit Retail Bank",
    tisco:	"Tisco Bank",
    ttb:	"TMBThanachart Bank",
    uob:	"United Overseas Bank (Thai)"
}

export default bankCodes;